### PR TITLE
(MAINT) Use Docker build stages to compose image

### PR DESCRIPTION
**Pull request by johnmccabe**
This PR uses the build stages feature to build the client and subsequent image from the same Dockerfile.

It requires the use of the current edge release `17.05`.

### CODE REVIEW

**Comment by garethr** [comment]
I'm a big +1 on merging this, just checking with @jfryman, @tylerpace and @kenazk that you have 17.05 and don't see this as a problem.

**Comment by jfryman** [comment]
LGTM :+1:. 

I run 17.05.0-ce.

**Comment by johnmccabe** [comment]
If/when Docker Hub supports multi-stage builds then this is gonna be awesome to enable switching to an automated hub build rather than the Travis image push - *if* that happens.

**Comment by johnmccabe** [comment]
ping @tylerpace / @kenazk

**Comment by tylerpace** [comment]
👍

**Comment by johnmccabe** [comment]
@puppetlabs/lumogon can I get this merged when green please

**Pull request merged**
