### PR TITLE
(MAINT) Add the hostname on which the report was generated

### PR DESCRIPTION
**Pull request by garethr**
This came up talking to a user today. We'll need to consider this and
a few of the other top level parameters when we look at Swarm and
multi-host reports but feels useful somewhere. This might want a
clearer name?

### CODE REVIEW

**Comment by rick** [comment]
Merged up and resolved conflicts due to #24, ran this locally and pushed a report up to https://reporter.app.lumogon.com/j99He6tQDjD6VSHkxKZxGCiaphOeE4gjbKv4dgtjrEM=

This `Host` information doesn't currently become part of the report (as far as I can see), but seeing the `Host` field in dynamodb like so:

dynamodb_ _aws_console

Does this look reasonable? I was expecting something like my laptop's `hostname`, but perhaps this is the id of the docker engine?

**Comment by rick** [comment]
If this is as intended then I'm :+1:

**Comment by johnmccabe** [comment]
agree, this looks like the hostname of the scheduler - @garethr is that what you'd intended?

**Comment by tylerpace** [comment]
Thoughts on renaming 'hostname' to 'Docker Node ID'? Hostname has a separate function than what is being gathered and presented here. For example:

```
➜  lumogon git:(master) docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
36sg8sc2aia52d71g7mrvx45f *  moby      Ready   Active        Leader
```

ID and HOSTNAME have different values, but I think we're only talking about collecting and presenting ID here?

**Comment by johnmccabe** [comment]
@garethr suggest we close this, open a new PR when the server identification is addressed.

**Pull request closed without merging**
